server:
  port: 9000

spring:
  application:
    name: ants

app:
  services:
    ants:
      name: ants-service
#      url: https://games-test.datsteam.dev/api
      url: https://games.datsteam.dev/api
      token: ??

logging:
  level:
    root: INFO
    ru:
      clever:
        antsattacks:
          client: DEBUG

feign:
  client:
    config:
      default:
        loggerLevel: FULL